In [42]:
import pandas as pd
import re

In [147]:
df = pd.read_csv("chart_data/bitcoin_candle2.csv")
del df["Unnamed: 0"]

In [148]:
df.head()

         Date      open      high       low     close  volume
0  2013-09-03  160000.0  160000.0  160000.0  160000.0    0.10
1  2013-09-04  150000.0  180000.0  150000.0  180000.0    3.64
2  2013-09-05  150000.0  160000.0  150000.0  160000.0    1.40
3  2013-09-06  145000.0  145000.0  145000.0  145000.0    0.20
4  2013-09-07  145000.0  145000.0  140000.0  140000.0    0.40

In [149]:
df['26_ewma'] = pd.ewma(df.close, span=26-1)
df['12_ewma'] = pd.ewma(df.close, span=12-1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: pd.ewm_mean is deprecated for Series and will be removed in a future version, replace with
	Series.ewm(span=25,min_periods=0,adjust=True,ignore_na=False).mean()
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: pd.ewm_mean is deprecated for Series and will be removed in a future version, replace with
	Series.ewm(span=11,min_periods=0,adjust=True,ignore_na=False).mean()

In [150]:
df['MACD'] = (df['12_ewma'] - df['26_ewma'])

In [151]:
df['signal'] = pd.ewma(df.MACD, span=9-1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: pd.ewm_mean is deprecated for Series and will be removed in a future version, replace with
	Series.ewm(span=8,min_periods=0,adjust=True,ignore_na=False).mean()
  """Entry point for launching an IPython kernel.

In [152]:
df.head(100)

,Date,open,high,low,close,volume,26_ewma,12_ewma,MACD,signal
0,2013-09-03,160000.0,160000.0,160000.0,160000.0,0.100000,160000.000000,1.600000e+05,0.000000,0.000000
1,2013-09-04,150000.0,180000.0,150000.0,180000.0,3.640000,170400.000000,1.709091e+05,509.090909,286.363636
2,2013-09-05,150000.0,160000.0,150000.0,160000.0,1.400000,166652.452026,1.665934e+05,-59.045432,141.399209
3,2013-09-06,145000.0,145000.0,145000.0,145000.0,0.200000,160573.162939,1.596423e+05,-930.838051,-234.399331
4,2013-09-07,145000.0,145000.0,140000.0,140000.0,0.400000,155774.981423,1.541690e+05,-1605.985508,-660.467079
5,2013-09-08,141000.0,160000.0,141000.0,146000.0,0.800000,153803.375117,1.521219e+05,-1681.432544,-951.854973
6,2013-09-10,142000.0,142000.0,142000.0,142000.0,0.240000,151686.747960,1.497819e+05,-1904.862929,-1207.683723
7,2013-09-11,140000.0,140000.0,140000.0,140000.0,0.600000,149785.703355,1.476575e+05,-2128.194497,-1443.871907
8,2013-09-12,144000.0,144000.0,144000.0,144000.0,0.220000,148918.886178,1.469014e+05,-2017.504677,-1586.167304
9,2013-09-13,144000.0,144000.0,144000.0,144000.0,0.630000,148232.007710,1.463247e+05,-1907.330805,-1663.828550
10,2013-09-14,135000.0,135000.0,135000.0,135000.0,0.100000,146493.322957,1.441437e+05,-2349.625885,-1826.476433
11,2013-09-17,144000.0,144000.0,144000.0,144000.0,0.100000,146182.626293,1.441167e+05,-2065.904151,-1882.424491
12,2013-09-18,144000.0,144000.0,144000.0,144000.0,0.100000,145923.025928,1.440953e+05,-1827.763152,-1869.796169
13,2013-09-20,144000.0,144000.0,144000.0,144000.0,0.400000,145703.524922,1.440780e+05,-1625.480341,-1813.844991
14,2013-09-23,142000.0,142000.0,142000.0,142000.0,0.200000,145295.961156,1.437077e+05,-1588.297059,-1762.540212
15,2013-09-24,142000.0,146000.0,142000.0,146000.0,4.180000,145370.954769,1.441116e+05,-1259.388469,-1648.686813
16,2013-09-25,142000.0,148000.0,141000.0,148000.0,2.500000,145642.948465,1.447902e+05,-852.720394,-1469.303159
17,2013-09-26,147000.0,148000.0,147000.0,148000.0,2.500000,145880.499246,1.453461e+05,-534.431263,-1259.275204
18,2013-09-27,141000.0,148000.0,131000.0,148000.0,5.046800,146089.130998,1.458027e+05,-286.448586,-1041.251763
19,2013-09-28,137000.0,148000.0,137000.0,148000.0,0.429300,146273.265244,1.461787e+05,-94.554902,-829.484830
20,2013-09-30,148000.0,148000.0,147500.0,147500.0,2.435135,146389.221267,1.464038e+05,14.597126,-640.948651
21,2013-10-01,140000.0,147500.0,140000.0,145000.0,2.321524,146260.177652,1.461655e+05,-94.645285,-519.063986
22,2013-10-03,139000.0,139000.0,135000.0,135000.0,4.178148,145230.666329,1.442761e+05,-954.577051,-616.144451
23,2013-10-05,139000.0,139000.0,139000.0,139000.0,0.028520,144669.145825,1.433855e+05,-1283.607098,-764.826585
24,2013-10-06,139000.0,140000.0,139000.0,140000.0,2.227950,144253.834459,1.428153e+05,-1438.529719,-914.818585
25,2013-10-07,140000.0,145000.0,138000.0,138000.0,1.575445,143704.177748,1.420057e+05,-1698.496259,-1089.222576
26,2013-10-08,139000.0,145000.0,139000.0,145000.0,1.103450,143816.833441,1.425084e+05,-1308.439330,-1137.992523
27,2013-10-09,145000.0,145000.0,145000.0,145000.0,3.000000,143918.675220,1.429262e+05,-992.478940,-1105.627725
28,2013-10-10,142000.0,142000.0,139000.0,139000.0,0.496000,143499.137105,1.422685e+05,-1230.631673,-1133.425383
29,2013-10-11,139500.0,139500.0,139500.0,139500.0,0.529500,143160.862925,1.418051e+05,-1355.727112,-1182.852047
...,...,...,...,...,...,...,...,...,...,...
70,2013-11-21,725001.0,890000.0,680000.0,888889.0,262.377163,486492.212627,6.349562e+05,148463.951717,109268.892639
71,2013-11-22,850000.0,940000.0,850000.0,914999.0,249.852728,519558.147745,6.816301e+05,162071.915443,121002.897869
72,2013-11-23,913999.0,1051811.0,886000.0,1001000.0,242.273139,556699.839411,7.348585e+05,178158.634870,133704.172895
73,2013-11-24,1000000.0,1020000.0,920000.0,999000.0,106.960424,590814.243646,7.788821e+05,188067.879107,145784.996599
74,2013-11-25,995000.0,1000000.0,940000.0,999000.0,213.597487,622290.921351,8.155685e+05,193277.556535,156338.898876
75,2013-11-26,999000.0,1025000.0,951000.0,1020000.0,255.986816,652953.862264,8.496404e+05,196686.568679,165305.047766
76,2013-11-27,1020000.0,1220000.0,1010000.0,1200000.0,454.108913,695123.114106,9.080337e+05,212910.625057,175884.064984
77,2013-11-28,1200000.0,1400000.0,1100000.0,1381000.0,549.225968,747985.605991,9.868615e+05,238875.895857,189882.249665
78,2013-11-29,1391000.0,1795000.0,1380000.0,1550001.0,720.906553,809789.967502,1.080718e+06,270928.169509,207892.454118
79,2013-11-30,1550001.0,1670000.0,1500000.0,1518000.0,260.120310,864358.021007,1.153598e+06,289240.460239,225969.788845
80,2013-12-01,1518000.0,1570000.0,1190000.0,1300000.0,448.413791,897920.242790,1.177999e+06,280078.500994,237993.947118
81,2013-12-02,1300000.0,1325000.0,1000001.0,1170000.0,769.266729,918879.026384,1.176666e+06,257786.593008,242392.312876
82,2013-12-03,1180000.0,1299000.0,1100000.0,1235000.0,651.570040,943227.736172,1.186388e+06,243160.282593,242562.972813
83,2013-12-04,1234000.0,1320000.0,1210000.0,1260000.0,737.470986,967624.163203,1.198657e+06,231032.521840,240000.650373
84,2013-12-05,1257000.0,1379000.0,900000.0,1130000.0,1478.879134,980128.488729,1.187214e+06,207085.413345,232686.153252
85,2013-12-06,1139900.0,1179999.0,1070000.0,1093000.0,371.611864,988819.815849,1.171512e+06,182691.766778,221576.289586
86,2013-12-07,1093001.0,1109000.0,600000.0,840000.0,1593.344710,977361.302804,1.116260e+06,138898.342247,203203.412394
87,2013-12-08,811000.0,900000.0,700000.0,780000.0,458.574471,962166.401408,1.060216e+06,98049.963434,179835.979286
88,2013-12-09,780000.0,1010000.0,765200.0,920000.0,758.316387,958920.216623,1.036847e+06,77926.751982,157189.484325
89,2013-12-10,920000.0,1048500.0,906000.0,1024000.0,452.345431,963930.079750,1.034706e+06,70775.727261,137986.427197
90,2013-12-11,1024000.0,1126500.0,921000.0,1049700.0,690.852471,970532.298427,1.037205e+06,66672.540904,122138.896908
91,2013-12-12,1047000.0,1047000.0,950000.0,970000.0,223.390451,970491.326430,1.026004e+06,55512.705764,107333.076652
92,2013-12-13,975000.0,1015000.0,946500.0,950500.0,257.185874,968952.632019,1.013420e+06,44467.394265,93362.925010
93,2013-12-14,950500.0,999980.0,945000.0,945000.0,124.304563,967109.126444,1.002017e+06,34907.561716,80372.844277
94,2013-12-15,943100.0,960000.0,880000.0,924000.0,328.523320,963791.386149,9.890139e+05,25222.520260,68117.216717
95,2013-12-16,923000.0,955000.0,851000.0,852500.0,291.715694,955226.569750,9.662616e+05,11035.018354,55432.283747
96,2013-12-17,860000.0,879000.0,650000.0,720000.0,1201.287371,937124.530411,9.252180e+05,-11906.541181,40468.100429
97,2013-12-18,720000.0,744000.0,462000.0,552000.0,1519.297053,907487.948257,8.630150e+05,-44472.958313,21592.309597
98,2013-12-19,583999.0,699000.0,515001.0,650000.0,819.304723,887674.012956,8.275125e+05,-60161.521850,3424.791498
99,2013-12-20,650000.0,759999.0,630000.0,710000.0,617.915091,874002.214358,8.079271e+05,-66075.138673,-12019.637430

In [153]:
df = df[(df['Date'] >= '2018-04-01')&(df['Date'] <= '2018-10-01')]

In [154]:
dff = df[['MACD','signal']]

In [164]:
balance = 10000000
num_coins = 0
invest_amount=0
buy=0
sell=0
hold=0

In [165]:
action_list=[]
for i in dff.values:
    if i[0] >= i[1]:
        action = 0
    else:
        action = 1
    action_list.append(action)

In [166]:
balance_list = []
for idx, action in enumerate(action_list):
    validity = True
    if action == 0:
        if balance < df.close.values[idx]:
            validity = False
        if validity:
            balance = balance - df.close.values[idx]
            invest_amount = df.close.values[idx]
            balance -= invest_amount  # 보유 현금을 갱신
            num_coins += 1  # 보유 코인 수를 갱신
            buy += 1  # 매수 횟수 증가
            balance_list.append(balance)

    elif action == 1:
        if num_coins <= 0:
            validity = False
        if validity:
            invest_amount = df.close.values[idx]
            num_coins -= 1  # 보유 코인 수를 갱신
            balance += invest_amount  # 보유 현금을 갱신
            sell += 1  # 매도 횟수 증가
            balance_list.append(balance)
    if validity == False:
        hold += 1

        balance_list.append(balance)

In [172]:
balance_list

[10000000,
 10000000,
 10000000,
 10000000,
 10000000,
 10000000,
 10000000,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 -5241000.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0,
 4946500.0]

In [171]:
len(df)

184

In [75]:
    def act(self, action, confidence):
        if not self.validate_action(action):
            action = Agent.ACTION_HOLD # action을 할 수 없으면 관망

        # 환경에서 현재 가격 얻기
        current_price = self.environment.get_price()

        # 즉시 보상 초기화
        self.immediate_reward = 0

        # 매수
        if action == Agent.ACTION_BUY:
            # 매수할 단위를 판단
            trading_unit = self.decide_trading_unit(confidence)
            balance = self.balance - current_price * (1 + self.TRADING_CHARGE) * trading_unit

            if balance < 0: # 보유 현금이 모자랄 경우 보유 현금으로 가능한 만큼 최대한 매수
                trading_unit = max(min(
                    int(self.balance / (current_price * (1 + self.TRADING_CHARGE))), self.max_trading_unit),
                    self.min_trading_unit
                )
            # 수수료를 적용하여 총 매수 금액 산정
            invest_amount = current_price * (1 + self.TRADING_CHARGE) * trading_unit
            self.balance -= invest_amount  # 보유 현금을 갱신
            self.num_coins += trading_unit  # 보유 코인 수를 갱신
            self.num_buy += 1  # 매수 횟수 증가
            #print("매수")

        # 매도
        elif action == Agent.ACTION_SELL:
            # 매도할 단위를 판단
            trading_unit = self.decide_trading_unit(confidence)
            # 보유 코인이 모자랄 경우 가능한 만큼 최대한 매도
            trading_unit = min(trading_unit, self.num_coins)
            # 수수료 거래세 적용하여 매도
            invest_amount = current_price * (1 - (self.TRADING_TAX + self.TRADING_CHARGE)) * trading_unit
            self.num_coins -= trading_unit  # 보유 코인 수를 갱신
            self.balance += invest_amount  # 보유 현금을 갱신
            self.num_sell += 1  # 매도 횟수 증가
            #print("매도")


        # 관망
        elif action == Agent.ACTION_HOLD:
            self.num_hold += 1  # 관망 횟수 증가


        # 포트폴리오 가치 갱신
        self.portfolio_value = self.balance + current_price * self.num_coins
        loss = ((self.portfolio_value - self.base_portfolio_value) / self.base_portfolio_value)

        # 즉시 보상 판단
        self.immediate_reward = 1 if loss >= 0 else -1

        # 지연 보상 판단
        if loss > self.delayed_reward_threshold:
            delayed_reward = 1 # 수익 -> reward 1
            self.base_portfolio_value = self.portfolio_value
        elif loss < -self.delayed_reward_threshold:
            delayed_reward = -1 # 손실 -> reward -1
            self.base_portfolio_value = self.portfolio_value
        else:
            delayed_reward = 0
        return self.immediate_reward, delayed_reward

[1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [4]:
df.columns = ['date', 'price','volume']

In [5]:
df.head()

         date     price  volume
0  2013090315  160000.0    0.10
1  2013090401  150000.0    0.20
2  2013090409  180000.0    2.94
3  2013090414  180000.0    0.50
4  2013090510  150000.0    0.10

In [17]:
import datetime
str(df.date[0])[:8]

'20130903'

In [22]:
print(datetime.datetime.strptime(str(df.date[0])[:8],"%Y%m%d"))

2013-09-03 00:00:00

In [24]:
df.date = [datetime.datetime.strptime(str(i)[:8],"%Y%m%d") for i in df.date]

In [26]:
unique = list(set(df.date))

In [27]:
unique = sorted(unique)

In [28]:
data = pd.DataFrame()

In [29]:
data["Date"] = unique

In [31]:
data['open'] = unique
data['high'] = unique
data['low'] = unique
data['close'] = unique
data['volume'] = unique

In [32]:
data['volume'].loc[0] = 1

In [33]:
data['volume'] = df.volume.groupby(df.date).sum().values

In [34]:
data['high'] = df.price.groupby(df.date).max().values

In [35]:
data['open'] = df.price.groupby(df.date).first().values

In [36]:
data['low'] = df.price.groupby(df.date).min().values

In [37]:
data['close'] = df.price.groupby(df.date).last().values

In [38]:
data.head()

        Date      open      high       low     close  volume
0 2013-09-03  160000.0  160000.0  160000.0  160000.0    0.10
1 2013-09-04  150000.0  180000.0  150000.0  180000.0    3.64
2 2013-09-05  150000.0  160000.0  150000.0  160000.0    1.40
3 2013-09-06  145000.0  145000.0  145000.0  145000.0    0.20
4 2013-09-07  145000.0  145000.0  140000.0  140000.0    0.40

In [39]:
data.to_csv("Bitcoin_candle2.csv")